# Generated by Django 6.1 on 2026-08-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiumcar', '0002_remove_category_description_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='box',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Коробка'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='no-color', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='car',
            name='motion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='car',
            name='probeg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='car',
            name='toplivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год выпуска'),
        ),
    ]
